import subprocess
import time
import os
import signal

class MinecraftBridge:
    def __init__(self, mc_path="minecraft", display=":99", resolution="1280x720"):
        self.mc_path = mc_path
        self.display = display
        self.resolution = resolution
        self.mc_process = None
        self.record_process = None

    def start_display(self):
        print(f"Starting Xvfb on {self.display}...")
        subprocess.Popen(["Xvfb", self.display, "-screen", "0", f"{self.resolution}x24"])
        os.environ["DISPLAY"] = self.display

    def start_recording(self, output_file):
        print(f"Starting ffmpeg recording to {output_file}...")
        # Capture the Xvfb display
        cmd = [
            "ffmpeg", "-f", "x11grab", "-video_size", self.resolution,
            "-i", self.display, "-c:v", "libx264", "-preset", "ultrafast",
            "-pix_fmt", "yuv420p", output_file, "-y"
        ]
        self.record_process = subprocess.Popen(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

    def start_minecraft(self):
        print("Starting Minecraft Forge 1.12.2...")
        # Finding the actual Forge jar generated by the installer
        forge_jars = [f for f in os.listdir(self.mc_path) if f.startswith("forge-") and f.endswith(".jar")]
        jar_to_run = forge_jars[0] if forge_jars else "forge-client.jar"

        # Using -cp for complex classpaths is usually required, but for a simplified
        # automation, we try to run the main jar.
        cmd = [
            "java", "-Xmx2G",
            "-Djava.library.path=versions/1.12.2/1.12.2-natives",
            "-cp", f"{jar_to_run}:lib/*",
            "net.minecraft.launchwrapper.Launch",
            "--gameDir", ".",
            "--version", "1.12.2",
            "--assetsDir", "assets",
            "--assetIndex", "1.12",
            "--userProperties", "{}",
            "--accessToken", "0",
            "--username", "AI_Player"
        ]
        self.mc_process = subprocess.Popen(cmd, cwd=self.mc_path)

    def send_baritone_command(self, command):
        print(f"Executing Baritone command: {command}")
        # Command is sent by writing to the 'chat' via a local mod or stdin bridge.
        # We use a helper file that a custom mod on the Minecraft side would read.
        with open(os.path.join(self.mc_path, "baritone_cmd.txt"), "w") as f:
            f.write(command)

    def stop_all(self):
        if self.record_process:
            self.record_process.send_signal(signal.SIGINT)
            self.record_process.wait()
            print("Recording stopped.")
        if self.mc_process:
            self.mc_process.terminate()
            print("Minecraft stopped.")

if __name__ == "__main__":
    bridge = MinecraftBridge()
    bridge.start_display()
    bridge.start_recording("test_capture.mp4")
    bridge.start_minecraft()
    time.sleep(10)
    bridge.stop_all()
